### PR TITLE
regen the discovery libraries

### PR DESCRIPTION
**Pull request by devoncarew**
Regen the discovery libraries w/ the latest version of the `discoveryapis_generator` package.

### CODE REVIEW

**Comment by devoncarew** [comment]
Only whitespace changes -

**Comment by lukechurch** [comment]
But very nice whitespace changes. Is there a change to a dependency we need to continue picking these up?

lgtm.

**Comment by devoncarew** [comment]
The people who regen the libraries just need to ensure that they've run `pub update` locally.

**Comment by devoncarew** [comment]
There may be some min. dep we can set as well...

**Pull request merged**
