### PR TITLE
Update to Dart 2.10.3

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
Hey @devoncarew, as of Dart 2.10.3 I now need to run `dartfmt` twice to get it to reach a fixpoint. Any ideas on who I should hassle?

brett

**Comment by domesticmouse** [comment]
Relevent [log lines](https://travis-ci.org/github/dart-lang/dart-services/jobs/740755925#L565) from Travis:

```
generate-protos
  protoc --dart_out=lib/src protos/dart_services.proto
  dartfmt --fix -w lib/src/protos
  Formatting directory lib/src/protos:
  Formatted dart_services.pb.dart
  Formatted dart_services.pbenum.dart
  Formatted dart_services.pbjson.dart
  Formatted dart_services.pbserver.dart
  dartfmt --fix -w lib/src/protos
  Formatting directory lib/src/protos:
  Formatted dart_services.pb.dart
  Unchanged dart_services.pbenum.dart
  Unchanged dart_services.pbjson.dart
  Unchanged dart_services.pbserver.dart
```

**Comment by devoncarew** [comment]
That's super odd and unexpected. I guess I would make sure that you are using the dartfmt from that sdk (2.10.3) - ensure that there's not some other version on your path. Do you know what the 2nd diff is?

2.10.3 is older, but if you can repro, you can file an issue w/ details against dart-lang/dart_style.

**Comment by domesticmouse** [comment]
@devoncarew the delta that the second run of `dartfmt` modifies is captured in https://github.com/dart-lang/dart-services/pull/613/commits/012986a45ac139d3ff38d7c968e2c1070f15a1c1

I'm not seeing this issue on the 2.11 beta, nor 2.10.2.

**Comment by domesticmouse** [comment]
Correction, I am also seeing this behaviour on `2.11.0-213.4.beta`

**Comment by domesticmouse** [comment]
Tracking issue raised: https://github.com/dart-lang/dart_style/issues/971

**Pull request merged**
