### PR TITLE
pub upgrade

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by domesticmouse** [comment]
The build blocker is tracked in https://github.com/google/dart-neats/issues/60

**Comment by domesticmouse** [comment]
Hey @devoncarew,

If I have `analyzer` at 0.39.17 I can't run the code generator, but pinning it to 0.39.16 works as intended. Any idea how to proceed with debugging this breakage?

```bash
$ pub run build_runner build --delete-conflicting-outputs
Precompiling executable... (9.5s)
Precompiled build_runner:build_runner.
[INFO] Generating build script completed, took 294ms
[INFO] Reading cached asset graph completed, took 69ms
[INFO] Checking for updates since last build completed, took 548ms
[WARNING] analyzer|lib/src/error/dart2js_verifier.dart was not found in the asset graph, incremental builds will not work.
 This probably means you don't have your dependencies specified fully in your pubspec.yaml.
[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds. completed, took 4ms
[INFO] Generating build script completed, took 55ms
[INFO] Creating build script snapshot... completed, took 9.7s
[INFO] Building new asset graph completed, took 583ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] shelf_router_generator:shelf_router on benchmark/bench.dart:

Bad state: Unexpected diagnostics:
/Users/brettmorgan/homebrew/Cellar/dart/2.9.2/libexec/lib/core/uri.dart:3259:39 - Expected an identifier.
[WARNING] No actions completed for 15.0s, waiting on:
  - shelf_router_generator:shelf_router on bin/server_cloud_run.dart
  - shelf_router_generator:shelf_router on bin/server_dev.dart
  - shelf_router_generator:shelf_router on bin/server.dart
  - shelf_router_generator:shelf_router on test/shelf_cors_test.dart
  - shelf_router_generator:shelf_router on test/analysis_server_test.dart
  .. and 11 more

[WARNING] No actions completed for 15.1s, waiting on:
  - shelf_router_generator:shelf_router on bin/server_cloud_run.dart
  - shelf_router_generator:shelf_router on bin/server_dev.dart
  - shelf_router_generator:shelf_router on bin/server.dart
  - shelf_router_generator:shelf_router on test/shelf_cors_test.dart
  - shelf_router_generator:shelf_router on test/analysis_server_test.dart
  .. and 11 more

[INFO] 41.2s elapsed, 1/17 actions completed.^C%                                                                                                                
```

**Comment by devoncarew** [comment]
> If I have analyzer at 0.39.17 I can't run the code generator, but pinning it to 0.39.16 works as intended. Any idea how to proceed with debugging this breakage?

I believe you're unblocked for the moment? Your question is how to resolve this in the future?

For now, you'll need to either pin analyzer here or build_runner; see https://github.com/dart-lang/build/issues/2763.

**Comment by domesticmouse** [comment]
Thanks for the context @devoncarew, I'm pinning `analyzer` until we upgrade to Dart 2.10.

TBR: @johnpryan

**Pull request merged**
