### PR TITLE
update code completion tests to account for the new ranking algorithm

### PR DESCRIPTION
**Pull request by devoncarew**
- update code completion tests to account for the new ranking algorithm

Some unit tests re-written to use async rather than futures, for easier debugging,

@domesticmouse @johnpryan

### CODE REVIEW

**Comment by johnpryan** [comment]
@domesticmouse the CI failure looks unrelated: `Failed to precompile protoc_plugin:protoc_plugin:`

**Comment by devoncarew** [comment]
> @domesticmouse the CI failure looks unrelated: `Failed to precompile protoc_plugin:protoc_plugin:`

The most recent publish of package:analyzer depends on a not-yet-published file in package:meta; we're looking at the breakage.

**Comment by devoncarew** [comment]
Restarting the build...

**Review by domesticmouse — COMMENTED** [review]
Lgtm, safe to delete the branch?

**Pull request merged**
