### PR TITLE
add a build task to generate the discovery document from the API

### LINKED ISSUE #54: generate the discovery document as part of the build process

### PR DESCRIPTION
**Pull request by devoncarew**
Fix #54 - generate the discovery document as part of our build.

@lukechurch, @wibling 

@wibling, what I'm doing now is starting a copy of the server, downloading the discovery document from the localhost URL, writing the file out, and killing the server. Would there be a more straightforward way of doing this? I imagine you need the annotations available at runtime to generate the doc. If the server could respond to a `--gen_doc` command-line flag, are there APIs in the `rpc` package the server could call to generate the doc w/o having to have a server running? As in, the server could either be invoked in a way to start up a server (the 99% use case), or invoked such that it just wrote out its discovery doc and exited?

### CODE REVIEW

**Comment by lukechurch** [comment]
@devoncarew lgtm

In general I like to keep a very explicit separation between things that are generated and things that are user created. Otherwise we can get oursevles into a mess losing edits by accident.

So could we put it in: doc/generated/dartservices.json?

**Comment by devoncarew** [comment]
> I like to keep a very explicit separation between things that are generated

Makes sense. I'm hoping that we'll soon have a generated dart library co-located with this discovery document. So, `dartservices.json` and `dartservices.dart`, or some similar name. In `doc/generated`, `doc/`, `generated/`?

**Comment by wibling** [comment]
Hi Devon,

If you want to do it without spinning up the server in a separate process you could do something like this change: https://codereview.chromium.org/948873002/

**Comment by devoncarew** [comment]
Thanks! I'll update this PR once https://codereview.chromium.org/948873002/ lands.

**Comment by devoncarew** [comment]
Merging - I think the build failure (VM segfault) is intermittent.

**Pull request merged**
