### PR TITLE
Add test corpus from gists

### PR DESCRIPTION
**Pull request by lukechurch**
@devoncarew 

As discussed with @danrubel it would be useful to have a corpus of public dart files that we can run the fuzz tester on ahead of each release. This adds a corpus based on the sample gists.

### CODE REVIEW

**Comment by danrubel** [comment]
LGTM

**Comment by devoncarew** [comment]
Re: the failures (https://travis-ci.org/dart-lang/dart-services/builds/242044827#L389), I'd suggest adding an excludes line in the analysis options to exlcude the corpus directory from analysis.

+1 to the corpus - sounds great. These files are going to get out of sync with the samples we ship however. I'd recommend adding a grind task to git clone the (10?) samples we ship with and move their dart source into the corpus. We can run this script manually - it'll be much easier to keep the corpus up to date.

lgtm w/ the analysis fix

**Comment by devoncarew** [comment]
(I did update those two samples to declare return types)

**Comment by lukechurch** [comment]
Thanks @devoncarew, I'll follow the grind task approach

**Pull request closed without merging**
