### PR TITLE
Upgrade to Flutter 1.21.0-9.2.pre

### PR DESCRIPTION
**Pull request by domesticmouse**
Upgrading to Flutter 1.21

### CODE REVIEW

**Comment by johnpryan** [comment]
I think the failure has something to do with the analysis when importing and using a library using the `required` keyword in a const constructor. The `SpringDescription` constructor in `flutter/lib/src/physics/spring_simulation.dart` uses the new `required` keyword:

```
  const SpringDescription({
    required this.mass,
    required this.stiffness,
    required this.damping,
  });
```

Doing a similar thing in the _same library_ will fail since null safety isn't enabled:

```
import 'package:flutter/material.dart';

void main() {
  var cat = Cat(size: 2);
  print(cat.size.runtimeType);
}

class Cat {
  final double size;
  const Cat({
    required this.size,
  });
}
```

`required isn't a type.  `
`Don't type annotate initializing formals.  `
`The parameter type 'dynamic' is incompatible with the field type 'double'.  `

@devoncarew @MichaelRFairhurst is it possible this is a bug in the analyzer?

**Comment by scheglov** [comment]
Yes, from `required isn't a type.` it looks to me that the code was analyzed without the `non-nullable` feature.
Which Dart SDK do you use?
Does it have `flutter` configured to have `non-nullable` in its `lib/_internal/allowed_experiments.json`?

**Comment by johnpryan** [comment]
It looks like Flutter `1.21.0-9.2.pre` uses Dart `2.10.0-7.3.beta`. It looks like `non-nullable` is enabled for the `flutter` package, where the `SpringDescription` class lives:

<details>
  <summary>allowed_experiments.json</summary>

```
{
  "version": 1,
  "experimentSets": {
    "nullSafety": [
      "non-nullable"
    ]
  },
  "sdk": {
    "default": {
      "experimentSet": "nullSafety"
    },
    "_example_libraries": {
      "ui": {
        "experimentSet": "nullSafety"
      }
    }
  },
  "packages": {
    "async": {
      "experimentSet": "nullSafety"
    },
    "boolean_selector": {
      "experimentSet": "nullSafety"
    },
    "characters": {
      "experimentSet": "nullSafety"
    },
    "charcode": {
      "experimentSet": "nullSafety"
    },
    "clock": {
      "experimentSet": "nullSafety"
    },
    "collection": {
      "experimentSet": "nullSafety"
    },
    "convert": {
      "experimentSet": "nullSafety"
    },
    "crypto": {
      "experimentSet": "nullSafety"
    },
    "csslib": {
      "experimentSet": "nullSafety"
    },
    "dart_internal": {
      "experimentSet": "nullSafety"
    },
    "fake_async": {
      "experimentSet": "nullSafety"
    },
    "file": {
      "experimentSet": "nullSafety"
    },
    "fixnum": {
      "experimentSet": "nullSafety"
    },
    "flutter": {
      "experimentSet": "nullSafety"
    },
    "flutter_test": {
      "experimentSet": "nullSafety"
    },
    "flutter_goldens": {
      "experimentSet": "nullSafety"
    },
    "flutter_goldens_client": {
      "experimentSet": "nullSafety"
    },
    "js": {
      "experimentSet": "nullSafety"
    },
    "matcher": {
      "experimentSet": "nullSafety"
    },
    "meta": {
      "experimentSet": "nullSafety"
    },
    "path": {
      "experimentSet": "nullSafety"
    },
    "pedantic": {
      "experimentSet": "nullSafety"
    },
    "platform": {
      "experimentSet": "nullSafety"
    },
    "pool": {
      "experimentSet": "nullSafety"
    },
    "process": {
      "experimentSet": "nullSafety"
    },
    "sky_engine": {
      "experimentSet": "nullSafety"
    },
    "source_maps": {
      "experimentSet": "nullSafety"
    },
    "source_map_stack_trace": {
      "experimentSet": "nullSafety"
    },
    "source_span": {
      "experimentSet": "nullSafety"
    },
    "stack_trace": {
      "experimentSet": "nullSafety"
    },
    "stream_channel": {
      "experimentSet": "nullSafety"
    },
    "string_scanner": {
      "experimentSet": "nullSafety"
    },
    "term_glyph": {
      "experimentSet": "nullSafety"
    },
    "test": {
      "experimentSet": "nullSafety"
    },
    "test_api": {
      "experimentSet": "nullSafety"
    },
    "test_core": {
      "experimentSet": "nullSafety"
    },
    "typed_data": {
      "experimentSet": "nullSafety"
    },
    "vector_math": {
      "experimentSet": "nullSafety"
    }
  }
}

```

</details>

**Comment by scheglov** [comment]
OK, I see that it is in this file.

Is there a way for me to reproduce this issue?

**Comment by johnpryan** [comment]
One way is to checkout this branch of dart-services and run the tests:

```
git clone git@github.com:dart-lang/dart-services.git
git submodule update --init
flutter/bin/flutter doctor
flutter/bin/flutter config --enable-web
flutter/bin/flutter precache --web --no-android --no-ios --no-linux --no-windows --no-macos --no-fuchsia
grind test
```

**Comment by johnpryan** [comment]
I also tried reproducing this another way, but wasn't able to see the same exception. I checked out flutter:

```bash
git clone git@github.com:flutter/flutter.git
cd flutter
git checkout 81a45ec2e5f80fa71d5135f1702ce540558b416d
flutter doctor
```

Then created a test project (outside the flutter directory) and pasted in this code:

```bash
/<path to flutter directory>/flutter/bin/flutter create test_project
cd test_project 
rm -rf test
```

edited lib/main.dart and pasted in this code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/physics.dart';

main() {
  runApp(
    MaterialApp(
      debugShowCheckedModeBanner: false,
      home: PhysicsCardDragDemo(),
    ),
  );
}

class PhysicsCardDragDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('A draggable card!'),
      ),
      body: DraggableCard(
        child: FlutterLogo(
          size: 128,
        ),
      ),
    );
  }
}

class DraggableCard extends StatefulWidget {
  final Widget child;
  DraggableCard({this.child});

  @override
  _DraggableCardState createState() => _DraggableCardState();
}

class _DraggableCardState extends State<DraggableCard>
    with SingleTickerProviderStateMixin {
  AnimationController _controller;
  Alignment _dragAlignment = Alignment.center;
  Animation<Alignment> _animation;

  void _runAnimation(Offset pixelsPerSecond, Size size) {
    _animation = _controller.drive(
      AlignmentTween(
        begin: _dragAlignment,
        end: Alignment.center,
      ),
    );

    final unitsPerSecondX = pixelsPerSecond.dx / size.width;
    final unitsPerSecondY = pixelsPerSecond.dy / size.height;
    final unitsPerSecond = Offset(unitsPerSecondX, unitsPerSecondY);
    final unitVelocity = unitsPerSecond.distance;

    const spring = SpringDescription(
      mass: 30,
      stiffness: 1,
      damping: 1,
    );

    final simulation = SpringSimulation(spring, 0, 1, -unitVelocity);

    _controller.animateWith(simulation);
  }

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this);

    _controller.addListener(() {
      setState(() {
        _dragAlignment = _animation.value;
      });
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    return GestureDetector(
      onPanDown: (details) {
        _controller.stop();
      },
      onPanUpdate: (details) {
        setState(() {
          _dragAlignment += Alignment(
            details.delta.dx / (size.width / 2),
            details.delta.dy / (size.height / 2),
          );
        });
      },
      onPanEnd: (details) {
        _runAnimation(details.velocity.pixelsPerSecond, size);
      },
      child: Align(
        alignment: _dragAlignment,
        child: Card(
          child: widget.child,
        ),
      ),
    );
  }
}
```

then run flutter analyze:

```bash
/<path to flutter directory>/flutter/bin/flutter analyze
Analyzing test_project...                                               
No issues found! (ran in 2.1s)
```

Which seems odd.

**Comment by johnpryan** [comment]
@domesticmouse It's also strange that the other tests in dart-services that analyze this snippet are passing. The only one that fails is the one that uses `CommonServerImpl`.

**Comment by domesticmouse** [comment]
My current suspicion is that there is some interaction on disk between the two Analysis Servers (one for Dart, one for Flutter) and the compilation tool chains. `CommonServerImpl` is responsible for managing the warmup and shutdown of all of these services, each of which generates on-disk artefacts. It is interesting to see that this [error condition is also visible](https://travis-ci.org/github/dart-lang/dart-services/jobs/723562808#L986) in https://github.com/dart-lang/dart-services/pull/583 which is based on Dart 2.10 but is running against Flutter 1.20.

**Comment by scheglov** [comment]
I did steps from [this comment]( https://github.com/dart-lang/dart-services/pull/584#issuecomment-685997053).
I see two tests failing.
It does not look to be analyzer related.
```
  00:00 +2 -1: test/redis_cache_test.dart: RedisCache (setUpAll) [E]
    ProcessException: No such file or directory
      Command: redis-server --port 9501
    dart:io                           Process.start
    test/redis_cache_test.dart 40:25  defineTests.<fn>.startRedisProcessAndDrainIO
    test/redis_cache_test.dart 52:55  defineTests.<fn>.<fn>
    ===== asynchronous gap ===========================
    dart:async                        _asyncThenWrapperHelper
    test/redis_cache_test.dart        defineTests.<fn>.<fn>

  00:00 +2 -2: test/analysis_server_test.dart: Platform SDK analysis_server simple_completion
  00:00 +2 -2: test/redis_cache_test.dart: RedisCache (tearDownAll) [E]
    NoSuchMethodError: The method 'shutdown' was called on null.
    Receiver: null
    Tried calling: shutdown()
    dart:core                         Object.noSuchMethod
    test/redis_cache_test.dart 72:37  defineTests.<fn>.<fn>
    ===== asynchronous gap ===========================
    dart:async                        _AsyncAwaitCompleter.completeError
    test/redis_cache_test.dart        defineTests.<fn>.<fn>

  00:01 +3 -2: loading test/flutter_web_test.dart
```

**Comment by johnpryan** [comment]
I think I forgot to add the step to check out this branch (`gh pr checkout 584` if you have the `gh` command tool installed)

We suspect this has something to do with extra files (perhaps in `.dart_tool/`) existing in the Flutter project being analyzed, since there aren't any errors in a brand new Flutter project. We'll keep investigating to find better steps to reproduce.

**Comment by domesticmouse** [comment]
@scheglov The test suite depends on Redis, and I'm guessing you don't have that installed. The master branch is currently green and should not error out. 

In my investigations I've come to understand that both of the Analyzers share the same project directory, and I can make the tests currently in this branch pass by duplicating the project directories to give each analyzer their own directory, but I'm still getting errors out of DartPad so there is another issue somewhere.

Expect a series of cleanup PRs as I move things around to split up currently tangled responsibilities.

**Comment by domesticmouse** [comment]
Turns out, the issue was that the Dart Analysis Server in 2.9 didn't mind if the project directory didn't exist at startup, but the new NNBD code does. The fix was in https://github.com/dart-lang/dart-services/pull/600

**Pull request merged**
