### PR TITLE
Enforce two strict analysis modes

### PR DESCRIPTION
**Pull request by srawlins**
I like these changes for a few specific reasons:

* `Future` => `Future<void>` ensures with static analysis you won't try to use the result.
* `Future` => `Future<AnalysisServer>` changes any method/field access on the result from dynamic dispatch to static dispatch; safer, smaller, faster.
* `Future` => `Future<dynamic>` is not really a functional improvement; it lucks ugly. But it takes code that was already using dynamic (just secretly) and makes it explicit, so that developers are aware of dynamicism in their code.

Some changes like `{}` => `<dynamic, dynamic>{}` are pretty ugly. I hope that with generalized typedefs, some styles come out like `typedef JsonMap = Map<dynamic, dynamic>`, etc.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Review by parlough — APPROVED** [review]

**Comment by domesticmouse** [comment]
This change is impacting the compilation phase. That's probably bad. This may need to wait until after we implement the single sdk change.

/cc @devoncarew

**Comment by devoncarew** [comment]
DBC: do we want to update the flutter submodule as part of this change? It may be best to keep that separate from this PR.

**Comment by srawlins** [comment]
I think they should definitely be different changes.

**Comment by srawlins** [comment]
OK it was the analysis_options causing problems. This is ready for review now.

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
