### PR TITLE
add the 'code' and 'column' fields to analysis issues

### PR DESCRIPTION
**Pull request by devoncarew**
- add the 'code' and 'column' fields to analysis issues

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]
LGTM

Please note, landing this has to be aligned with publishing the updated front end, otherwise the front end will be sad and not work.

**Comment by devoncarew** [comment]
> LGTM
> 
> Please note, landing this has to be aligned with publishing the updated front end, otherwise the front end will be sad and not work.

I'm assuming that the frontend just won't see these fields - that the previous protos and generated files will still work against a newer backend?

**Comment by devoncarew** [comment]
It's not critical that these fields be available right away, it would just be nice for them to be there eventually.

**Comment by domesticmouse** [comment]
> > LGTM
> 
> > 
> 
> > Please note, landing this has to be aligned with publishing the updated front end, otherwise the front end will be sad and not work.
> 
> 
> 
> I'm assuming that the frontend just won't see these fields - that the previous protos and generated files will still work against a newer backend?

No, it is serving as JSON. I have a maintenance task to rip out protobuf and replace it with one of the JSON code generation approaches, but I've never had the time to revisit. 

You need to push both at the same time. I've caused outages recently by landing the backend before the front end was ready to land.

**Comment by domesticmouse** [comment]
> It's not critical that these fields be available right away, it would just be nice for them to be there eventually.

Do you want to mark this PR as a Draft until you are ready to add the fields to the front end?

**Comment by devoncarew** [comment]
@domesticmouse - feel free to land these 2 PRs now or whenever we're ready to do the next push

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
