### PR TITLE
Refactor AnalysisServerWrapper with simpler init

### PR DESCRIPTION
**Pull request by srawlins**
Simplify AnalysisServerWrapper a bit:

* `_init` is unused except for "has it been assigned yet" so changed to `bool`.
* `init`'s return value is never used, so instead make it return void.

### CODE REVIEW

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
Looks like this code needs to be fixed: https://github.com/dart-lang/dart-services/runs/2949223890#step:7:8

**Comment by srawlins** [comment]
Thanks!

**Comment by domesticmouse** [comment]
Any reason not to land this PR?

**Comment by srawlins** [comment]
Sorry, was on vacation; thanks!

**Pull request merged**
