### PR TITLE
Update to Dart 2.10

### PR DESCRIPTION
**Pull request by domesticmouse**
This is blocked on https://github.com/dart-lang/dart-pad/issues/1616

### CODE REVIEW

**Comment by domesticmouse** [comment]
@devoncarew I suspect I'm going to need your support in debugging these failures before the next Flutter stable release.

**Comment by devoncarew** [comment]
> @devoncarew I suspect I'm going to need your support in debugging these failures before the next Flutter stable release.

Sure; feel free to set up a VC.

**Comment by domesticmouse** [comment]
TBR @johnpryan

**Review by johnpryan — COMMENTED** [review]
LGTM

**Pull request merged**
