### PR TITLE
Give the Dart Analysis Servers a config

### PR DESCRIPTION
**Pull request by domesticmouse**
Fix: https://github.com/dart-lang/dart-pad/issues/1784

### CODE REVIEW

**Review by srawlins — APPROVED** [review]
I'm not sure how the title matches the changes, but I like the changes!

**Comment by domesticmouse** [comment]
@srawlins the core of this change is in `lib/src/analysis_server.dart`. Previously the Dart Analysis server was fed an empty directory as it's working directory, so it started enforcing null safety when we rolled over to dart 2.12. This change gives the Dart Analysis server a populated directory with a `pubspec.yaml` this is enough to stop the dart analysis server enforcing null safety rules.

Now if only I could figure out how to unbreak the Github Actions...

**Comment by srawlins** [comment]
Ah I get it; makes sense. No ideas about the GitHub Actions :(

**Comment by domesticmouse** [comment]
replaced by https://github.com/dart-lang/dart-services/pull/680

**Pull request closed without merging**
