### PR TITLE
Use pkg:lints and pkg:flutter_lints

### PR DESCRIPTION
**Pull request by domesticmouse**
fixes: https://github.com/dart-lang/dart-pad/issues/1881

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @gspencergoog

**Review by srawlins — APPROVED** [review]
Yesss! Very cool

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

Excellent, thank you!

**Comment by RedBrogdon** [comment]
What effect, if any, will this have for existing DartPad-based codelabs? It looks like `flutter_lints` includes at least a few lint rules we're not already using:

https://github.com/flutter/packages/blob/master/packages/flutter_lints/lib/flutter.yaml

The `avoid_print` one in particular could be problematic for any Flutter embeds that use print statements to output things to the console.

**Comment by RedBrogdon** [comment]
(to be clear, I definitely support the change. I'm just wondering what additional work is required and whether now is the right moment).

**Comment by domesticmouse** [comment]
@RedBrogdon I'm happy to hold this change for a week.

**Comment by domesticmouse** [comment]
Hey @johnpryan and @RedBrogdon ,

I'd like to land this PR, but it is going to flag our samples as having linter errors. When are you going to have time to patch the flutter drop down exxample code?

brett

**Comment by mit-mit** [comment]
I sent a PR for the /samples repo (https://github.com/dart-lang/samples/pull/112). Is this a different set of samples?

**Comment by domesticmouse** [comment]
Yup, it's the gists that DartPad loads when you use the menu in the top right hand corner.

**Comment by domesticmouse** [comment]
Replaced by https://github.com/dart-lang/dart-services/pull/722

**Pull request closed without merging**
