### PR TITLE
Import of dart:ui to trigger Flutter compilation

### PR DESCRIPTION
**Pull request by domesticmouse**
Partial fix for: https://github.com/dart-lang/dart-pad/issues/1518

### CODE REVIEW

**Comment by dnfield** [comment]
Nice!  Thanks

**Comment by domesticmouse** [comment]
Hey @dnfield, do you have a minimal `dart:ui` sample that should run in Flutter for web that I could use to test this? I'll go ahead and push this to prod so we can poke at it and confirm this is WAI.

**Comment by dnfield** [comment]
```dart
import 'dart:ui';

void main() {
  print(window.physicalSize);
}
```

**Comment by dnfield** [comment]
(or really, just any property of the global `window` object)

**Comment by domesticmouse** [comment]
Win! Thanks @dnfield, I'll ping you when it's up =)

**Comment by domesticmouse** [comment]
Actually I think this also requires a front end change to make it work. Currently the front end thinks this isn't a Flutter and it is sending it to the Dart compilation API. 

```
Error compiling to JavaScript:
main.dart:1:8:
Error: Not found: 'dart:ui'
import 'dart:ui';
       ^
main.dart:4:9:
Error: Getter not found: 'window'.
  print(window.physicalSize);
        ^^^^^^
Error: Compilation failed.
```

@RedBrogdon I'm going to land this change as is and re-assign https://github.com/dart-lang/dart-pad/issues/1518 to you and @johnpryan for required front end changes.

**Comment by domesticmouse** [comment]
TBR: @RedBrogdon

**Pull request merged**
