### PR TITLE
re-enable tests against dev

### PR DESCRIPTION
**Pull request by devoncarew**
- see if we can re-enable tests with the dev dart sdk (https://github.com/dart-lang/dart-pad/issues/1002)
- update some dartdoc comments for lib/src/compiler.dart

### CODE REVIEW

**Comment by devoncarew** [comment]
Closing - the test timeouts are still an issue.

**Comment by domesticmouse** [comment]
I'm going to re-open this PR as I believe this should now be land-able.

**Comment by domesticmouse** [comment]
Actually, it looks like this PR is [failing on dev branch](https://travis-ci.org/dart-lang/dart-services/jobs/526677436) while my [PR is succeeding](https://travis-ci.org/dart-lang/dart-services/jobs/526598841). 

I'm confused.

**Comment by devoncarew** [comment]
Not sure why it's not consistent, but it looks like something about our tests keeps the 2.3.0-dev sdk running after the tests finish. Perhaps something (a process?) we're not cleanup up?

It'd be useful to see if we can repro this locally.

**Comment by domesticmouse** [comment]
Attempting to replicate with the following configuration.

```bash
$ uname -a
Linux dart-2dot3-tester 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux
$ dart --version
Dart VM version: 2.3.0-dev.0.3 (Unknown timestamp) on "linux_x64"
```

Unfortunately this works fine on the command line after pulling the `test_with_dev` branch.

**Comment by domesticmouse** [comment]
Entertainingly this now passes on `2.3.0`, but times out on `2.3.1-dev.0.0`.

**Pull request closed without merging**
