### PR TITLE
Add URL, correction, and diagnostic messages to AnalysisIssue messages

### PR DESCRIPTION
**Pull request by johnpryan**
This enables https://github.com/dart-lang/dart-pad/issues/1676

### CODE REVIEW

**Comment by parlough** [comment]
Did you mean to commit the modified `pubspec.lock`?

**Review by domesticmouse — APPROVED** [review]

**Comment by johnpryan** [comment]
I think the `pubspec.lock` is fine to commit (I'm using the 2.10.5 SDK, which is probably better?)

**Review by parlough — APPROVED** [review]

**Comment by domesticmouse** [comment]
I'll land this for both stable and null safety later today.

**Comment by domesticmouse** [comment]
Actually, you’ll need to fix the tests first. Cant land it broken 🤪

**Comment by johnpryan** [comment]
Should be safe to deploy without dart-lang/dart-pad#1676 – protobufs are neat.

**Comment by domesticmouse** [comment]
Yup, my read is you'll want this serving on production so you can properly test https://github.com/dart-lang/dart-pad/issues/1676

**Comment by domesticmouse** [comment]
Hey @johnpryan,

Actually, turns out using JSON makes the upside of protobufs not work out. I deployed this to both the mainline and the null safety endpoints and I wound up with errors with parsing lint warnings from the analyzer. I've rolled back the servers to yesterday's version. Please try rolling forward https://github.com/dart-lang/dart-pad/issues/1676 and see if it works, otherwise we will need to do a co-ordinated release.

/cc @RedBrogdon

**Comment by johnpryan** [comment]
I need to make a few more tweaks anyway. I'll see if we can deploy the frontend first.

**Comment by domesticmouse** [comment]
Feel free to throw a half hour on my cal when you want to roll forward, as re-deploying these versions for me is a couple of clicks in the Cloud Run console

**Pull request merged**
