### PR TITLE
Enable generic method support

### PR DESCRIPTION
**Pull request by lukechurch**
@devoncarew PTAL

This updates master to the 1.21 branch and enables support and a test for generic method.

The tests are mainly passing, so I'm preping a server update.

### CODE REVIEW

**Comment by lukechurch** [comment]
I have a suspicion that the travis warnings are due to strong mode changes. I'll look into them

**Comment by lukechurch** [comment]
I think Devon is out, @danrubel PTAL?

**Comment by lukechurch** [comment]
I need to move this forwards to support testing. TBRing for now. Happy to address feedback afterwards. @danrubel

**Comment by danrubel** [comment]
LGTM

**Comment by lukechurch** [comment]
Thanks @danrubel

**Comment by devoncarew** [comment]
Sorry - was out; lgtm2!

**Pull request merged**
