### PR TITLE
Rotating journal logs

### PR DESCRIPTION
**Pull request by domesticmouse**
Rotating and vacuuming journal log files to prevent running out of disk space on `/`.

### CODE REVIEW

**Comment by domesticmouse** [comment]
It's the file that is growing without bound on the instances, so at this point I believe it is the cause of the outages.

**Comment by domesticmouse** [comment]
And reformatted the code for line length

**Comment by jonasfj** [comment]
I'm curious, what is writing logs? I just checked out staging site, and we don't seem to have processes that write log files..

**Comment by domesticmouse** [comment]
It's the base OS that runs the Docker instance that houses the AppEngine Flex images, along with fluentd logging and nginx networking sidecars. It basically looks like Kubernetes + Istio, but I think it predates that tech. The logfile in question is controlled with `journalctl`, and can be easily rotated and culled, but I can't control the base image that runs AppEngine Flex. I'd much prefer if it were running Container Optimised OS instead of Debian Stretch.

**Pull request merged**
