### PR TITLE
Windows fixes, part 1

### PR DESCRIPTION
**Pull request by domesticmouse**
**DO NOT SUBMIT:** Pending product decision regarding https://github.com/dart-lang/dart-pad/issues/1493

This is the start of a fix for https://github.com/dart-lang/dart-pad/issues/1493

This PR is required, but not sufficient, to make `dart-services` run on MS Windows. The rest of the fixes are pending #488 landing.

### CODE REVIEW

**Comment by domesticmouse** [comment]
Hey @devoncarew, I'm hitting an issue with tuneup on windows. It is erroring out like this:

```bash

    error - The argument type 'FlutterSdk (where FlutterSdk is defined in C:\src\dart-services\lib\src\sdk_manager.dart)' can't be assigned to the parameter type 'FlutterSdk (where FlutterSdk is defined in c:\src\dart-services\lib\src\sdk_manager.dart)' at lib\services_dev.dart:84:49 - (argument_type_not_assignable)
    error - The argument type 'FlutterSdk (where FlutterSdk is defined in C:\src\dart-services\lib\src\sdk_manager.dart)' can't be assigned to the parameter type 'FlutterSdk (where FlutterSdk is defined in c:\src\dart-services\lib\src\sdk_manager.dart)' at lib\services_dev.dart:119:43 - (argument_type_not_assignable)
    error - The argument type 'FlutterSdk (where FlutterSdk is defined in C:\src\dart-services\lib\src\sdk_manager.dart)' can't be assigned to the parameter type 'FlutterSdk (where FlutterSdk is defined in c:\src\dart-services\lib\src\sdk_manager.dart)' at lib\services_gae.dart:78:49 - (argument_type_not_assignable)
```

Any ideas?

**Comment by devoncarew** [comment]
> Hey @devoncarew, I'm hitting an issue with tuneup on windows. It is erroring out like this:
> 
> ```shell
>     error - The argument type 'FlutterSdk (where ...
> ```
> 
> Any ideas?

I'd make sure that there's just one SDK, or, that there's no ambiguity about which sdk is being used for analysis.

You may also be running into an issue where a type defined from a relative import isn't necessarily the same type as that defined from a package: import (even if the imports resolve to the same file on disk). You can solve that by making sure that you always use consistent imports within `lib/`. I generally prefer to use relative imports within `lib/` (and package: imports other places).

Try turning on the `prefer_relative_imports` lint and see if you find any package: self-reference imports.

**Comment by domesticmouse** [comment]
Hey @devoncarew, thanks for the `prefer_relative_imports` hint. We did indeed have one `package:` self reference for `SdkManager`.

**Comment by domesticmouse** [comment]
We decided not to support MS Windows for deployment of the server at this point in time.

**Pull request closed without merging**
